import images from './images';

// data.js
const appetizer = [
  {
    id: 'a1',
    title: 'Crab Rangoon (5 pcs.)',
    price: 7,
    category: 'Appetizers',
    spicy: 0,
    description: 'Crabstick and cream cheese filling inside crispy wonton wrappers.',
    image: images.thai,
  },
  {
    id: 'a2',
    title: 'Egg Rolls (4 pcs.)',
    price: 7,
    category: 'Appetizers',
    spicy: 0,
    description: 'Crispy vegetables rolls served with sweet & sour sauce.',
    image: images.thai2,
  },
  {
    id: 'a3',
    title: 'Chicken Satay (4 pcs.)',
    price: 8,
    category: 'Appetizers',
    spicy: 0,
    description: 'Grilled marinated chicken on skewers served with peanut sauce on the side.',
    image: images.thai3,
  },
  {
    id: 'a4',
    title: 'Moo Ping (4 pcs.)',
    price: 8,
    category: 'Appetizers',
    spicy: 0,
    description: 'Marinated grilled pork on a stick, served with sweet chili sauce',
    image: images.thai2,
  },
  {
    id: 'a5',
    title: 'Pork Dumpling (5 pcs.)',
    price: 8,
    category: 'Appetizers',
    spicy: 0,
    description: 'Choose either steamed or deep-fried served with ginger soy dip.',
    image: images.thai2,
  },
  {
    id: 'a6',
    title: 'Wings (5 pcs.)',
    price: 12,
    category: 'Appetizers',
    spicy: 2,
    description: 'Choose crispy or spicy fish sauce.',
    image: images.thai2,
  },
  {
    id: 'a7',
    title: 'Sweater Shrimp (4 pcs.)',
    price: 7,
    category: 'Appetizers',
    spicy: 0,
    description: 'Marinated shrimp wrapped in spring roll skin served with sweet & sour sauce.',
    image: images.thai2,
  },
  {
    id: 'a8',
    title: 'Crispy Pork Belly (5 pcs.)',
    price: 12,
    category: 'Appetizers',
    spicy: 0,
    description: 'Marinated prok belly sprinkled with sesame seed, crispy onion and garlic served with spicy sauce.',
    image: images.thai2,
  },
  {
    id: 'a9',
    title: 'Street Ball (5 pcs.)',
    price: 10,
    category: 'Appetizers',
    spicy: 1,
    description: 'Chicken, roasted rice, onion, kaffir lime leaf served with spicy lime sauce.',
    image: images.thai2,
  },
  {
    id: 'a10',
    title: 'Edamame',
    price: 6,
    category: 'Appetizers',
    spicy: 0,
    description: 'Steamed soybean seasoned with salt',
    image: images.thai2,
  },
  {
    id: 'a11',
    title: 'Sauna Mussels',
    price: 12,
    category: 'Appetizers',
    spicy: 2,
    description: 'Steamed mussels with lemongrass and sweet basil leafs served with spicy Thai garlic sauce.',
    image: images.thai2,
  },
  {
    id: 'a12',
    title: 'Fresh Rolls',
    price: 7,
    category: 'Appetizers',
    spicy: 0,
    description: 'Steamed vermicelli, grilled chicken, lettuce, carrot, cucumber, basil leaf wrapped in rice paper served with homemade sweet sauce, ground peanuts. Can be made vegetarian.',
    image: images.thai2,
  },
  {
    id: 'a13',
    title: 'Sampler',
    price: 15,
    category: 'Appetizers',
    spicy: 0,
    description: 'Combination of (2) Egg Rolls, (2) Sweater Shrimp, (2) Crab Rangoon, and (3) Pork Dumplings served with ginger soy dip and sweet & sour sauce.',
    image: images.thai2,
  },
];

const soup = [
  {
    id: 'so1',
    title: 'Tom Kha Soup',
    price: '7 (Pot 18)',
    category: 'Soup',
    spicy: 0,
    description: 'Coconut milk soup with galangal root, mushroom, tomatoes, scallion, cilantro, choice of meat.',
    image: images.thai,
  },
  {
    id: 'so2',
    title: 'Tom Yum Soup',
    price: '7 (Pot 18)',
    category: 'Soup',
    spicy: 1,
    description: 'Spicy & sour soup, mushrooms, tomatoes, scallion, cilantro and choice of meat.',
    image: images.thai,
  },
  {
    id: 'so3',
    title: 'Miso Soup',
    price: 7,
    category: 'Soup',
    spicy: 0,
    description: 'A healthy traditional Japanese soup with tofu, seaweed and scallion.',
    image: images.thai,
  },
];

const salad = [
  {
    id: 'sal1',
    title: 'Larb E-San',
    price: 13,
    category: 'Salad',
    spicy: 2,
    description: 'Lettuce wraps, minced chicken mixed with red onion, lemongrass, cilantro, roasted rice in a spicy lime dressing.',
    image: images.thai,
  },
  {
    id: 'sal2',
    title: 'Papaya Salad',
    price: 12,
    category: 'Salad',
    spicy: 2,
    description: 'Thai style, sweet & sour with peanut or Laos style, spicy & sour with salted crab.',
    image: images.thai,
  },
  {
    id: 'sal3',
    title: 'Neua Nam Tok',
    price: 15,
    category: 'Salad',
    spicy: 2,
    description: 'Grilled sliced beef mixed with lime juice, chili powder, roasted rice, red onion, kaffir lime leaf. Very delicious!',
    image: images.thai,
  },
  {
    id: 'sal4',
    title: 'Woon Sen Salad',
    price: 15,
    category: 'Salad',
    spicy: 2,
    description: 'Clear noodles, ground chicken, shrimp, onion, scallion, cilantro with spicy house lime dressing.',
    image: images.thai,
  },
]

const unique = [
  {
    id: 'u1',
    title: 'Pla Rad Pik',
    price: 20,
    category: 'Unique',
    spicy: 2,
    description: 'Crispy tilapia top with sweet chili sauce.',
    image: images.thai,
  },
  {
    id: 'u2',
    title: 'Mango Chicken',
    price: 15,
    category: 'Unique',
    spicy: 1,
    description: 'Sliced chicken stir-fried in our chefs special sweet and sour sauce with slieced mango, peppers, and onion.',
    image: images.thai,
  },
  {
    id: 'u3',
    title: 'Chili Tamarind Chicken',
    price: 14,
    category: 'Unique',
    spicy: 2,
    description: 'Crispy chicken coated with spicy tamarind sauce served on bed of steamed vegetables.',
    image: images.thai,
  },
  {
    id: 'u4',
    title: "Soi 2's Company Dish ",
    price: 15,
    category: 'Unique',
    spicy: 0,
    description: 'A classic combination of shrimp, chicken and beef sauteed with mix vegetables in a delicate sauce, sprinkled with sesame seed.',
    image: images.thai,
  },
  {
    id: 'u5',
    title: 'Basil Duck',
    price: 18,
    category: 'Unique',
    spicy: 2,
    description: 'Boneless duck is fried crispy with onion, bell in a spicy Thai basil sauce.',
    image: images.thai,
  },
  {
    id: 'u6',
    title: 'Combination Seafood',
    price: 18,
    category: 'Unique',
    spicy: 2,
    description: 'Calamari, shrimp, mussels, scallops, basil, onion, bell, scallions with sweet chili sauce.',
    image: images.thai,
  },
  {
    id: 'u7',
    title: 'Street Steak',
    price: 22,
    category: 'Unique',
    spicy: 0,
    description: 'Marinated steak with garlic sauce, mix veggie, served with house spicy sauce.',
    image: images.thai,
  },
]

const mom = [
  {
    id: 'mom1',
    title: 'Larb Mae Janla',
    price: 15,
    category: 'Mom',
    spicy: 3,
    description: 'This is my original home town food, mince chicken with a spicy herb paste, served with lettuce and cucumber.',
    image: images.thai,
  },
  {
    id: 'mom2',
    title: 'Gaeng Hang Lay',
    price: 15,
    category: 'Mom',
    spicy: 1,
    description: 'Very delicious pork belly slow cook Northern style curry, ginger, garlic, tamarind. You must try!',
    image: images.thai,
  },
]

const veg = [
  {
    id: 'v1',
    title: 'Eggplant',
    price: 14,
    category: 'Veggie',
    spicy: 1,
    description: 'Stir fried eggplant, pepper, onion with homemade brown sauce and a taste of sweet basil leaf.',
    image: images.thai,
  },
  {
    id: 'v2',
    title: 'Vegetable Bouquet',
    price: 13,
    category: 'Veggie',
    spicy: 0,
    description: 'Golden fried tofu on a bed of steamed assorted vegetables and served with side of peanut sauce.',
    image: images.thai,
  },
  {
    id: 'v3',
    title: 'Crispy Mock Duck',
    price: 15,
    category: 'Veggie',
    spicy: 1,
    description: 'A good source of protein. Choose between red curry or Gra Pow sauce.',
    image: images.thai,
  },
]

const dessert = [
  {
    id: 'des1',
    title: 'Mango & Sticky Rice',
    price: 8,
    category: 'Dessert',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 'des2',
    title: 'Thai Custard & Sticky Rice',
    price: 8,
    category: 'Dessert',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 'des3',
    title: 'Tapioca & Taro',
    price: 8,
    category: 'Dessert',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
]

const noodlesoup = [
  {
    id: 'ns1',
    title: 'Duck Noodles',
    price: 18,
    category: 'Noodle Soup',
    spicy: 0,
    description: 'Bean sprout, crispy garlic, scallion, cilantro in a slow cook duck broth.',
    image: images.thai,
  },
  {
    id: 'ns2',
    title: 'Lek Heng Tom Yum',
    price: 14,
    category: 'Noodle Soup',
    spicy: 1,
    description: 'Ground chicken, peanut, bean sprout, crispy garlic, fried wonton skin, scallion, cilantro.',
    image: images.thai,
  },
  {
    id: 'ns3',
    title: 'Khao Soi',
    price: 16,
    category: 'Noodle Soup',
    spicy: 1,
    description: 'Northern-style Ramen noodle soup prepared with beef or chicken, crunchy wontons, pickled cabbage, red onion, crispy onion, crispy garlic, cilantro and scallion in a curry stock.',
    image: images.thai,
  },
  {
    id: 'ns4',
    title: 'Thai Beef Soup',
    price: 15,
    category: 'Noodle Soup',
    spicy: 0,
    description: 'Tender beef, meat balls, bean sprouts, cilantro, scallion, crispy garlic.',
    image: images.thai,
  },
  {
    id: 'ns5',
    title: 'Tom Yum Talay Noodles',
    price: 18,
    category: 'Noodle Soup',
    spicy: 2,
    description: 'A spicy Tom Yum broth with minced chicken, seafood, bean sprouts, ground peanut, cilantro and scallion.',
    image: images.thai,
  },
]

const curry = [
  {
    id: 'c1',
    title: 'Red Curry',
    price: 0,
    category: 'Curry',
    spicy: 2,
    description: 'Bell pepper, egg plant, basil.',
    image: images.thai,
  },
  {
    id: 'c2',
    title: 'Gaeng Sub Pa Rod',
    price: 0,
    category: 'Curry',
    spicy: 1,
    description: 'Bell, pineapples, basil.',
    image: images.thai,
  },
  {
    id: 'c3',
    title: 'Massaman Curry',
    price: 0,
    category: 'Curry',
    spicy: 1,
    description: 'Potato, onion, carrots, cinnamon, peanut.',
    image: images.thai,
  },
  {
    id: 'c4',
    title: 'Green Curry',
    price: 0,
    category: 'Curry',
    spicy: 1,
    description: 'Bamboo shoots, egg plant, bell, basil.',
    image: images.thai,
  },
  {
    id: 'c5',
    title: 'Mango Curry',
    price: 0,
    category: 'Curry',
    spicy: 1,
    description: 'Mango, onions, carrots, tomatoes.',
    image: images.thai,
  },
  {
    id: 'c6',
    title: 'Kha Ree Curry',
    price: 0,
    category: 'Curry',
    spicy: 1,
    description: 'Potato, onion, carrots.',
    image: images.thai,
  },
  {
    id: 'c7',
    title: 'Panang Curry',
    price: 0,
    category: 'Curry',
    spicy: 1,
    description: 'Bell pepper, basil & kaffir lime leaf.',
    image: images.thai,
  },
]

const noodle = [
  {
    id: 'n1',
    title: 'Pad Thai',
    price: 0,
    category: 'Noodle',
    spicy: 0,
    description: 'Choice of meat stir-fried with rice noodles, eggs, scallions, bean sprouts, peanuts.',
    image: images.thai,
  },
  {
    id: 'n2',
    title: 'Fiery Pad Thai',
    price: 15,
    category: 'Noodle',
    spicy: 1,
    description: 'Spicy version of traditional Pad Thai, with chicken and shrimp, egg, onion, carrots, peppers, and basil.',
    image: images.thai,
  },
  {
    id: 'n3',
    title: 'Pad Kee Mao',
    price: 0,
    category: 'Noodle',
    spicy: 2,
    description: 'Wide noodles with your choice of meat, egg, onion, carrots, bell, basil leaf with spicy basil sauce.',
    image: images.thai,
  },
  {
    id: 'n4',
    title: 'Pad Woon Sen',
    price: 0,
    category: 'Noodle',
    spicy: 0,
    description: 'A healthy dish of glass noodles sauteed with a homemade sauce, egg and mix veggies.',
    image: images.thai,
  },
  {
    id: 'n5',
    title: 'Pad See U',
    price: 0,
    category: 'Noodle',
    spicy: 0,
    description: 'Choice of meat stir-fried with wide noodles, eggs, broccoli, carrots in a sweet dark soy sauce.',
    image: images.thai,
  },
  {
    id: 'n6',
    title: 'Lion City Noodles',
    price: 0,
    category: 'Noodle',
    spicy: 2,
    description: 'Vermicelli noodles stir fried with Tahi spicy sauce, egg, seasoned with curry powder, carrots, peas, sprouts, onion and scallions, with choice of meat.',
    image: images.thai,
  },
  {
    id: 'n7',
    title: 'Bangkok Lo Mein',
    price: 0,
    category: 'Noodle',
    spicy: 0,
    description: 'Egg Noodle stir fried with mixed veggies in brown homemade sauce, with choice of meat.',
    image: images.thai,
  },
  {
    id: 'n8',
    title: 'Rad Nah',
    price: 15,
    category: 'Noodle',
    spicy: 0,
    description: 'Wide rice noodles, your choice of meat, broccoli and carrots in a gravy sauce.',
    image: images.thai,
  },
]

const wok = [
  {
    id: 'w1',
    title: 'Gra Pow',
    price: 15,
    category: 'Wok',
    spicy: 2,
    description: 'Minced chicken, basil, bell pepper, onion stir fried in a spicy Thai basil sauce. Served with fried egg on the top.',
    image: images.thai,
  },
  {
    id: 'w2',
    title: 'Chicken Ginger',
    price: 0,
    category: 'Wok',
    spicy: 0,
    description: 'White chicken stir fried with ginger sauce, onion, red bell peppers, shiitake mushroom and scallions.',
    image: images.thai,
  },
  {
    id: 'w3',
    title: 'Pad Pak',
    price: 0,
    category: 'Wok',
    spicy: 0,
    description: 'Choice of meat with mixed vegetable wok in a homemade gravy sauce.',
    image: images.thai,
  },
  {
    id: 'w4',
    title: 'Garlic Sauce',
    price: 0,
    category: 'Wok',
    spicy: 0,
    description: 'Choice of meat, onion, black pepper and cilantro.',
    image: images.thai,
  },
  {
    id: 'w5',
    title: 'Cashew Nut',
    price: 0,
    category: 'Wok',
    spicy: 1,
    description: 'Choice of meat, onion, peppers, carrot, cashew nut, scallion, sweet chili sauce.',
    image: images.thai,
  },
  {
    id: 'w6',
    title: 'Sweet & Sour',
    price: 0,
    category: 'Wok',
    spicy: 0,
    description: 'Choice of meat, bell pepper, onion, cucumber, tomatoes, pineapples, and scallion.',
    image: images.thai,
  },
  {
    id: 'w7',
    title: 'Pad Ped',
    price: 0,
    category: 'Wok',
    spicy: 3,
    description: 'Choice of meat wok with spicy chili sauce, bell pepper, bamboo shoot, onion, basil and kaffir lime leaf.',
    image: images.thai,
  },
]

const friedrice = [
  {
    id: 'f1',
    title: 'Thai Fried Rice',
    price: 0,
    category: 'Fried Rice',
    spicy: 0,
    description: 'Egg, onion, scallions, choice of meat.',
    image: images.thai,
  },
  {
    id: 'f2',
    title: 'Green Fried Rice',
    price: 0,
    category: 'Fried Rice',
    spicy: 1,
    description: 'Green curry, coconut milk, egg, eggplant, bell, basil leaf.',
    image: images.thai,
  },
  {
    id: 'f3',
    title: 'Pineapple Fried Rice',
    price: 0,
    category: 'Fried Rice',
    spicy: 0,
    description: 'Curry fried rice, egg, pineapple, raisin, cashew, scallions, your choice of meat.',
    image: images.thai,
  },
  {
    id: 'f4',
    title: 'Spicy Basil Fried Rice',
    price: 0,
    category: 'Fried Rice',
    spicy: 2,
    description: 'Egg, bell, onion and basil leaf in a spicy basil sauce, your choice of meat.',
    image: images.thai,
  },
  {
    id: 'f5',
    title: 'Combo Fried Rice',
    price: 0,
    category: 'Fried Rice',
    spicy: 0,
    description: 'Combination fried rice with Chicken, Beef, and Shrimp, egg, tomatoes, onion, broccoli and scallions.',
    image: images.thai,
  },
  {
    id: 'f6',
    title: 'Mango Fried Rice',
    price: 0,
    category: 'Fried Rice',
    spicy: 1,
    description: 'Choice of meat, egg, onion, mango, broccoli, scallion in a sweet & spicy sauce.',
    image: images.thai,
  },
  {
    id: 'f7',
    title: 'Crab Fried Rice',
    price: 18,
    category: 'Fried Rice',
    spicy: 0,
    description: 'Crab meat, egg, pea, carrot, scallion.',
    image: images.thai,
  },
  {
    id: 'f8',
    title: 'Street Fried Rice',
    price: 16,
    category: 'Fried Rice',
    spicy: 2,
    description: 'Spicy & sour fried rice, shrimps, egg, onion, lemongrass, kaffir lime leaf and cilantro.',
    image: images.thai,
  },
]

const drinks = [
  {
    id: 'd1',
    title: 'Thai Iced Coffee',
    price: 4,
    category: 'Drink',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 'd2',
    title: 'Thai Iced Tea',
    price: 4,
    category: 'Drink',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 'd3',
    title: 'Fountain Drink',
    price: 3,
    category: 'Drink',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 'd4',
    title: 'Hot Tea',
    price: 3,
    category: 'Drink',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 'd5',
    title: 'Unsweetened Thai Iced Tea',
    price: 3,
    category: 'Drink',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
]

const sides = [
  {
    id: 's1',
    title: 'White Rice',
    price: 3,
    category: 'Side',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 's2',
    title: 'Brown Rice',
    price: 3,
    category: 'Side',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 's3',
    title: 'Sticky Rice',
    price: 3,
    category: 'Side',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 's4',
    title: 'Fried Rice',
    price: 5,
    category: 'Side',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 's5',
    title: 'Peanut Sauce',
    price: 0.5,
    category: 'Side',
    spicy: 0,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 's6',
    title: 'Sweet Chili Sauce',
    price: 0.5,
    category: 'Side',
    spicy: 1,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 's7',
    title: 'Hot Sauce',
    price: 0.5,
    category: 'Side',
    spicy: 1,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
  {
    id: 's8',
    title: 'Thai Chili Fish Sauce',
    price: 1,
    category: 'Side',
    spicy: 1,
    description: 'Lorem Ipsum',
    image: images.thai,
  },
]

const featured = [
  {
    id: 'a13',
    title: 'Sampler',
    price: 15,
    category: 'Appetizers',
    spicy: 0,
    description: 'Combination of (2) Egg Rolls, (2) Sweater Shrimp, (2) Crab Rangoon, and (3) Pork Dumplings served with ginger soy dip and sweet & sour sauce.',
    image: images.thai2,
  },
  {
    id: 'so2',
    title: 'Tom Yum Soup',
    price: '7 (Pot 18)',
    category: 'Soup',
    spicy: 1,
    description: 'Spicy & sour soup, mushrooms, tomatoes, scallion, cilantro and choice of meat.',
    image: images.thai,
  },
  {
    id: 'sal2',
    title: 'Papaya Salad',
    price: 12,
    category: 'Salad',
    spicy: 2,
    description: 'Thai style, sweet & sour with peanut or Laos style, spicy & sour with salted crab.',
    image: images.thai,
  },
  {
    id: 'u2',
    title: 'Mango Chicken',
    price: 15,
    category: 'Unique',
    spicy: 1,
    description: 'Sliced chicken stir-fried in our chefs special sweet and sour sauce with slieced mango, peppers, and onion.',
    image: images.thai,
  },
  {
    id: 'mom1',
    title: 'Larb Mae Janla',
    price: 15,
    category: 'Mom',
    spicy: 3,
    description: 'This is my original home town food, mince chicken with a spicy herb paste, served with lettuce and cucumber.',
    image: images.thai,
  },
  {
    id: 'ns1',
    title: 'Duck Noodles',
    price: 18,
    category: 'Noodle Soup',
    spicy: 0,
    description: 'Bean sprout, crispy garlic, scallion, cilantro in a slow cook duck broth.',
    image: images.thai,
  },
  {
    id: 'c1',
    title: 'Red Curry',
    price: 0,
    category: 'Curry',
    spicy: 2,
    description: 'Bell pepper, egg plant, basil.',
    image: images.thai,
  },
  {
    id: 'n2',
    title: 'Fiery Pad Thai',
    price: 15,
    category: 'Noodle',
    spicy: 1,
    description: 'Spicy version of traditional Pad Thai, with chicken and shrimp, egg, onion, carrots, peppers, and basil.',
    image: images.thai,
  },
  {
    id: 'w1',
    title: 'Gra Pow',
    price: 15,
    category: 'Wok',
    spicy: 2,
    description: 'Minced chicken, basil, bell pepper, onion stir fried in a spicy Thai basil sauce. Served with fried egg on the top.',
    image: images.thai,
  },
  {
    id: 'f3',
    title: 'Pineapple Fried Rice',
    price: 0,
    category: 'Fried Rice',
    spicy: 0,
    description: 'Curry fried rice, egg, pineapple, raisin, cashew, scallions, your choice of meat.',
    image: images.thai,
  },
]

const menu = {
  appetizer,
  soup,
  salad,
  unique,
  mom,
  veg,
  dessert,
  noodlesoup,
  curry,
  noodle,
  wok,
  friedrice,
  drinks,
  sides,
  featured,
}

export default menu;
